apiVersion: v1
kind: Service
metadata:
  name: mal-web-service
spec:
  type: NodePort
  selector:
    app: mal-web
  ports:
    - name: mal-web-port
      protocol: TCP
      port: 3001
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mal-web-deployment
  labels:
    app: mal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mal-web
  template:
    metadata:
      generateName: mal-web-pod-
      labels:
        app: mal-web
    spec:
      containers:
        - name: malweb
          image: malweb:0.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80